### PR TITLE
Add the up to date "Artifex" name to Ghostscript list

### PR DESCRIPTION
**Pull request by chris-liddell**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/ImageMagick/ImageMagick6/pulls) open
- [x] I have verified that I am following the existing coding patterns and practices as demonstrated in the repository.

### CODE REVIEW

**Comment by dlemstra** [comment]
Can you explain why we need to add this? Since which version did they change this?

**Comment by chris-liddell** [comment]
> Can you explain why we need to add this? Since which version did they change this?

In order to find the registry keys. You already have "Aladdin Ghostscript" in your list, but "Aladdin" has not been the copyright holder, commercial arm of Ghostscript for some time. It's over 20 years since that changed to Artifex.

**Comment by dlemstra** [comment]
Can you provide some proof that this is what they are using as the registry key?

**Comment by dlemstra** [comment]
Found some proof here: https://bugs.ghostscript.com/show_bug.cgi?id=690266

**Pull request merged**
